name: cookingenie
description: Taazaa Inc product

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.13.0+58

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  http: ^0.13.3
  geolocator: ^12.0.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.3
  connectivity: ^3.0.6
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  fluttertoast: ^8.2.6
  streaming_shared_preferences: ^2.0.0
  pin_input_text_field: ^4.5.1
  flutter_svg: ^1.1.6
  dotted_border: ^2.1.0
  syncfusion_flutter_datepicker: 20.4.44
  flutter_rating_bar: ^4.0.1
  path: ^1.9.0
  meta: ^1.12.0
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  location_permissions: ^4.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  infinite_scroll_pagination: ^4.0.0
  dio: ^4.0.6
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^4.6.0
  uuid: ^3.0.6
  flutter_app_badger: ^1.3.0
  sizer: ^2.0.15
  get: ^4.6.5
  local_auth: ^2.1.0
  flutter_secure_storage: ^5.0.2
  dotted_line: ^3.1.0
  jiffy: ^6.3.1
  flutter_image_compress: ^1.1.0
  mime_type: ^1.0.0
  visibility_detector: ^0.3.3
  encrypted_shared_preferences: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  firebase_core: ^3.0.0
  http_interceptor: ^1.0.2
  sentry_flutter: ^7.9.0
  new_version_plus: ^0.0.9
  firebase_database: ^11.0.0
  location: ^4.4.0
  flutter_background_service: ^3.0.1
  wakelock: ^0.6.1+2
  webview_flutter: ^3.0.4
  file_picker: ^5.2.4
  video_player: ^2.4.10
  flutter_downloader: ^1.10.2
  readmore: ^2.2.0
  google_fonts: ^4.0.3
  url_launcher: ^6.0.9
  pull_to_refresh: ^2.0.0
  lottie: ^2.3.2
  auto_size_text: ^3.0.0
  flutter_multi_formatter: ^2.11.0
  maps_launcher: ^2.2.0
  section_view: ^2.0.5
  html: ^0.15.4
  flutter_lints: ^3.0.1
  sprintf: ^7.0.0
  open_file_plus: ^3.4.1+1
  downloads_path_provider_28: ^0.1.2
  image_cropper: ^7.0.5
  flutter_localizations:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dependency_overrides:
  http: ^0.13.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  freezed: ^2.4.1
  injectable_generator: ^1.4.1
  flutter_launcher_icons: ^0.9.1
  mockito: ^5.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpaceGrotes
      fonts:
        - asset: assets/fonts/SpaceGrotesk_Bold.ttf
        - asset: assets/fonts/SpaceGrotesk_Light.ttf
        - asset: assets/fonts/SpaceGrotesk_Medium.ttf
        - asset: assets/fonts/SpaceGrotesk_Regular.ttf
        - asset: assets/fonts/SpaceGrotesk_SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
